### ISSUE TITLE
Create mask is incompatible with 2D data

### ISSUE THREAD

**Issue by SaraDupont** [neuropoly/spinalcordtoolbox#1066]
`sct_create_mask`doesn't work with 2D data but the error message is not related to data dimensions. We have two possibilities:
 - adapt `sct_create_mask` to 2D data 
 - Display an error message specifying that 2D data are not supported

Data in `folder_shared/sct_issues/20161208_issue1066`
Command: `sct_create_mask -i im_sc.nii.gz -p centerline,im_sc.nii.gz -o mask.nii.gz`

**Comment by SaraDupont** [comment]
Looks like the issue doesn't happen with every 2D data, I'm investigating.

**Comment by SaraDupont** [comment]
The issue came from a wrong estimation of the orientation. --> fixed in commit 06dc32f

**Comment by SaraDupont** [comment]
`sct_crop_image` was creating a bug also, fixed in commit 8cbface

**Comment by SaraDupont** [comment]
fixed with PR #1067

**Comment by alexfoias** [comment]
Problem still presists in 3.0_beta32.

Data in `/folder_shared/sct_issues/20161208_issue1066/gre_ax_phantom.nii.gz`
Command: `sct_create_mask -i gre_ax_phantom.nii.gz -p center -size 20 -f cylinder`

**Comment by SaraDupont** [comment]
Fixed in PR #1180
