### ISSUE TITLE
[sct_register_to_template] Data image and segmentation are not in the same space.

### ISSUE THREAD

**Issue by SaraDupont** [neuropoly/spinalcordtoolbox#1168]
Fail happens in `sct_register_to_template`, on line 223 because of the precision of check_if_same_space() (4th decimal). 
--> Using 2d or 3d decimal fixes the issue. 

Do we need to keep a 4th decimal precision or can we just set the precision to the 2d decimal for example ?

**Comment by jcohenadad** [comment]
this seems to be related to https://github.com/neuropoly/spinalcordtoolbox/pull/1137, which is now fixed.

could you please try with this new version? space between seg and input image should be the same.

**Comment by SaraDupont** [comment]
I'm up-to-date with master and the bug is still there. 
Command : `sct_register_to_template -i Ax_t2c.nii.gz -s Ax_t2c_seg_manual.nii.gz -l Ax_t2c_labels.nii.gz`
Data in : 
`folder_shared/sct_issues/20170217_issue1168`

**Comment by jcohenadad** [comment]
how was the manual segmentation created? I guess it was generated before the PR (while bug was still there).
The PR only affected the generation of the segmentation (i.e. propseg).
to overcome this issue, you can simply copy the header img-->img_seg

**Comment by SaraDupont** [comment]
Yes it was. I'll copy the qform and sform of the image to the segmentation. 
But it means it can also happen for users who have segmentations from before the PR that they already manually corrected.

**Comment by jcohenadad** [comment]
yes that's right. The problem is that, if we accept lower precision, we might miss matrices which should be the same (and we will also miss correcting for segmentations done before the PR). For users who experience this issue (it has already happened), we recommended to add a line of code in their batch script to copy the header
