### ISSUE TITLE
batch_processing: check if fslview is executable before calling it

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1547]
### Description

Currently, if user does not have fslview, the command will crash. We can check if `fslview`is executable, and if not we set `$DISPLAYQC=false`.

**Comment by abtahizadeh** [comment]
- Fslview no more called at the end of process if it is deprecated
Fixed via #1648  ?

**Comment by jcohenadad** [comment]
@abtahizadeh  #1648 was addressing Python code inside SCT. `batch_processing` is a shell script, so issue is still relevant-- however the recent updates on `batch_processing` removed the display call. so we can close it.

**Comment by abtahizadeh** [comment]
yeah, I didn't see the command in batch_processing, I agree to close this.
