### ISSUE TITLE
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found

### ISSUE THREAD

**Issue by alexfoias** [neuropoly/spinalcordtoolbox#2523]
When running SCT on a Debian Wheezy (7.11), it crashes when trying to import modules of PyQt5, due to missing GLIB_2.14 which is missing in this distros.

to reproduce:
~~~
alfoi_admin@ferguson:~$ source ${SCT_DIR}/python/etc/profile.d/conda.sh
alfoi_admin@ferguson:~$ conda activate venv_sct
(venv_sct) alfoi_admin@ferguson:~$ python
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyQt5.QtCore
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /home/alfoi_admin/spinalcordtoolbox/python/envs/venv_sct/lib/python3.6/site-packages/PyQt5/QtCore.so)
~~~

info about version:
~~~
(venv_sct) alfoi_admin@ferguson:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.11 (wheezy)
Release:	7.11
Codename:	wheezy
~~~

**Comment by jcohenadad** [comment]
@alexfoias is this issue fixed by https://github.com/neuropoly/spinalcordtoolbox/pull/2524?

**Comment by alexfoias** [comment]
i'll have to test it.

**Comment by alexfoias** [comment]
@jcohenadad Rolling back the pyqt version doesn't seem to fix the issue.

Here is the output:
```
Validate installation...


--
Spinal Cord Toolbox (git-master-473e0c7d8243625a7b01423eaff0c9ce1de54aa5)

SCT info:
- version: git-master-473e0c7d8243625a7b01423eaff0c9ce1de54aa5
- path: /home/alfoi_admin/spinalcordtoolbox
OS: linux (Linux-3.2.0-4-amd64-x86_64-with-debian-7.11)
CPU cores: Available: 4, Used by SCT: 4
RAM: MemTotal:       16379384 kB
total       used       free     shared    buffers     cached
Mem:         15995       7708       8286          0        637       5745
-/+ buffers/cache:       1326      14669
Swap:        19312          0      19312
Check Python executable.............................[OK]
  Using bundled python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) 
[GCC 7.3.0] at /home/alfoi_admin/spinalcordtoolbox/python/envs/venv_sct/bin/python
Check if data are installed.........................[OK]
Check if numpy is installed.........................[OK] (1.17.4)
Check if cryptography is installed..................[OK] (2.8)
Check if dipy is installed..........................[OK] (1.0.0)
Check if futures is installed.......................[OK]
Check if h5py is installed..........................[OK] (2.10.0)
Check if Keras is installed.........................[OK] (2.3.1)
Check if matplotlib is installed....................[OK] (3.1.2)
Check if nibabel is installed.......................[OK] (2.5.1)
Check if pandas is installed........................[OK] (0.25.3)
Check if psutil is installed........................[OK] (5.6.7)
Check if pyqt5 (5.11.3) is installed................[WARNING] (None != 5.11.3 mandated version))
Check if pytest is installed........................[OK] (5.3.1)
Check if pytest-cov is installed....................[OK] (2.8.1)
Check if raven is installed.........................[OK]
Check if requests is installed......................[OK] (2.22.0)
Check if scipy is installed.........................[OK] (1.3.3)
Check if scikit-image is installed..................[OK] (0.16.2)
Check if scikit-learn is installed..................[OK] (0.21.3)
Check if tensorflow is installed....................[OK] (2.0.0)
Check if xlrd is installed..........................[OK] (1.2.0)
Check if xlutils is installed.......................[OK]
Check if xlwt is installed..........................[OK] (1.3.0)
Check if tqdm is installed..........................[OK] (4.39.0)
Check if transforms3d is installed..................[OK] (0.3.1)
Check if urllib3[secure] is installed...............[OK] (1.25.7)
Check if spinalcordtoolbox is installed.............[OK]
Check ANTs compatibility with OS ...................[OK]
Check PropSeg compatibility with OS ................[OK]
Check if figure can be opened.......................[OK]

alfoi_admin@ferguson:~/spinalcordtoolbox$ source /home/alfoi_admin/.bashrc
alfoi_admin@ferguson:~/spinalcordtoolbox$ source ${SCT_DIR}/python/etc/profile.d/conda.sh
alfoi_admin@ferguson:~/spinalcordtoolbox$ conda activate venv_sct
(venv_sct) alfoi_admin@ferguson:~/spinalcordtoolbox$ python
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyQt5.QtCore
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /home/alfoi_admin/spinalcordtoolbox/python/envs/venv_sct/lib/python3.6/site-packages/PyQt5/QtCore.so)

```

**Comment by jcohenadad** [comment]
wontfix 😞

**Comment by jcohenadad** [comment]
I experienced the same error on a centos6 distros. This is quite annoying...
