### ISSUE TITLE
installer do "rm -rf" of the installation folder --> To be modified with a patch today or tomorow

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/spinalcordtoolbox#708]
Someone got "big" problem today..

**Comment by benjamindeleener** [comment]
This issue is fixed in branch issue_708. It will be merge to the branch release and master as soon as the tests pass.

**Comment by tanguyduval** [comment]
Cool thanks!

**Comment by jcohenadad** [comment]
A patch does not solve it since issue is on the installation.
We need to make a new release asap
